server:
  port: 8888

dubbo:
  application:
    name: provider
  protocol:
    name: dubbo
    port: 12345

  registry:
    #address: N/A
    #address: multicast://224.0.0.1:4666?unicast=fasle
    #address: zookeeper://192.168.0.200:2181
    address: redis://192.168.0.200:6379
    #client: curator、zkclient，默认为curator